#!/bin/bash

cd `dirname $0`/../../
if [ -e pid.txt ]; then
	PID=`cat pid.txt`
	if ps ax | grep $PID | grep -q freepopsd; then
		kill $PID
		Contents/MacOS/fmessage 'FreePOPs stopped.'
		exit 0
	fi
	rm -f pid.txt
fi
	
#src/freepopsd -w -b 127.0.0.1 -l log.txt &
src/freepopsd -b 127.0.0.1 &
echo $! > pid.txt
Contents/MacOS/fmessage 'FreePOPs started. To stop it, double click again.' 

# eof
