// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef updater_h
#define updater_h
#include <FL/Fl.H>
extern bool updater_fast_quit;
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *updater_main_win;
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *updater_wiz_main;
#include <FL/Fl_Group.H>
extern Fl_Group *updater_grp_page_html;
#include <FL/Fl_Help_View.H>
extern Fl_Help_View *updater_hlp_page_html;
extern Fl_Group *updater_grp_page_select;
#include <FL/Fl_Check_Browser.H>
extern Fl_Check_Browser *updater_chkbrw_select;
extern Fl_Group *updater_grp_page_download;
#include <FL/Fl_Progress.H>
extern Fl_Progress *updater_prg_page_download;
#include <FL/Fl_Button.H>
extern Fl_Button *updater_btn_quit;
extern Fl_Button *updater_btn_next;
#include <FL/Fl_Box.H>
extern Fl_Box *updater_box_logo;
extern Fl_Box *updater_box_title;
Fl_Double_Window* make_main_window();
void updater_failure();
#endif
